### ISSUE TITLE
README.md Slack link broken

### ISSUE THREAD

**Issue by lm1909** [qiskit-community/ibm-quantum-spring-challenge-2022#1]
The Qiskit Slack workspace [link in README.md](https://github.com/qiskit-community/ibm-quantum-spring-challenge-2022#stay-connected) is broken (gives `This link is no longer active To join this workspace, you’ll need to ask the person who originally invited you for a new link.`)

**Comment by InfamousPlatypus** [comment]
Yah, same. But Slack seems down for me, so I'm not sure if that's the issue.

**Comment by anamariarojas123** [comment]
This has been resolved. Please try again: https://ibm.co/joinqiskitslack

**Comment by kashish5599** [comment]
Link is broken again.

**Comment by anamariarojas123** [comment]
This has been resolved. Please try again: https://ibm.co/joinqiskitslack
